# Generated by Django 5.1.4 on 2026-01-19 06:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name for this provider (e.g., 'Office Ollama', 'My Anthropic')", max_length=200, unique=True)),
                ('provider_type', models.CharField(choices=[('ollama', 'Ollama Server'), ('anthropic', 'Anthropic (Claude)')], help_text='Type of API provider', max_length=50)),
                ('base_url', models.CharField(blank=True, help_text="Base URL for API (e.g., 'http://192.168.1.100:11434' for Ollama)", max_length=500)),
                ('api_key', models.CharField(blank=True, help_text='API key for authentication (if required)', max_length=500)),
                ('is_local', models.BooleanField(default=False, help_text='True if this connects to localhost (use localhost instead of docker network name)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is currently active')),
                ('last_tested', models.DateTimeField(blank=True, help_text='Last time connection was successfully tested', null=True)),
                ('test_status', models.CharField(blank=True, help_text='Result of last connection test', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, help_text='UUID for this conversation', max_length=36, unique=True)),
                ('title', models.CharField(blank=True, default='New Conversation', help_text='Human-readable title for this conversation', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (inventory, game state, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DifficultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of this difficulty profile (e.g., 'Easy', 'Brutal')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this difficulty curve')),
                ('function', models.TextField(help_text="Python expression: returns probability. Variables: x (turn), n (max_turns). Example: '0.05 + 0.35 * (x/n)**2'")),
                ('curve_points', models.JSONField(blank=True, help_text='Array of 5 probability values for 0%, 25%, 50%, 75%, 100% progress', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this configuration preset', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this configuration')),
                ('storyteller_timeout', models.IntegerField(default=30, help_text='Timeout in seconds for storyteller generation (default: 30)')),
                ('turn_correction_timeout', models.IntegerField(default=30, help_text='Timeout in seconds for turn correction (default: 30)')),
                ('total_turns', models.IntegerField(choices=[(5, '5 turns'), (10, '10 turns'), (15, '15 turns'), (20, '20 turns')], default=10, help_text='Total number of turns in the adventure')),
                ('phase1_turns', models.IntegerField(default=3, help_text='Turns for Phase 1: Introduction/Exposition/Story Building')),
                ('phase2_turns', models.IntegerField(default=3, help_text='Turns for Phase 2: Victory/Loss Conditions')),
                ('phase3_turns', models.IntegerField(default=3, help_text='Turns for Phase 3: Progress/Narrative Twists')),
                ('phase4_turns', models.IntegerField(default=1, help_text='Turns for Phase 4: Finale/Conclusion Setup')),
                ('enable_refusal_detection', models.BooleanField(default=True, help_text='Enable automatic refusal detection and correction')),
                ('classifier_timeout', models.IntegerField(default=10, help_text='Timeout in seconds for classifier (default: 10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', models.ForeignKey(blank=True, help_text='Difficulty profile for death probability curve', null=True, on_delete=django.db.models.deletion.PROTECT, to='game.difficultyprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Unique session identifier from OpenWebUI filter', max_length=32, unique=True)),
                ('conversation_fingerprint', models.CharField(blank=True, db_index=True, help_text='Hash of first user + first assistant message for lookup when session ID is stripped', max_length=32, null=True)),
                ('turn_number', models.IntegerField(default=0, help_text='Current turn number (counts user messages after first assistant response)')),
                ('max_turns', models.IntegerField(default=20, help_text='Maximum turns for this game')),
                ('game_over', models.BooleanField(default=False, help_text='Whether this game has ended')),
                ('last_death_roll', models.FloatField(blank=True, help_text='Last random roll for death check (0.0-1.0)', null=True)),
                ('last_death_probability', models.FloatField(blank=True, help_text='Death probability on last turn', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(blank=True, help_text='Configuration snapshot when session started', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.configuration')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this model (shown in config dropdowns)', max_length=200, unique=True)),
                ('model_identifier', models.CharField(help_text="Backend model identifier (e.g., 'qwen3:4b', 'claude-opus-4')", max_length=200)),
                ('is_available', models.BooleanField(default=True, help_text='Whether this model is currently available for use')),
                ('capabilities', models.JSONField(blank=True, default=dict, help_text='Model capabilities and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(help_text='Provider hosting this model', on_delete=django.db.models.deletion.CASCADE, to='game.apiprovider')),
            ],
            options={
                'ordering': ['provider__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='classifier_model',
            field=models.ForeignKey(blank=True, help_text='Model to use for refusal classification', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configs_as_classifier', to='game.llmmodel'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='storyteller_model',
            field=models.ForeignKey(help_text='Model to use for story generation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configs_as_storyteller', to='game.llmmodel'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='turn_correction_model',
            field=models.ForeignKey(help_text='Model to use for turn correction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configs_as_turn_correction', to='game.llmmodel'),
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(db_index=True, help_text='Category: adventure, turn-correction, game-ending-correction, game-ending, classifier, judge', max_length=50)),
                ('name', models.CharField(db_index=True, default='default', help_text="Descriptive name for this prompt (e.g., 'haunted-house', 'v1-default')", max_length=100)),
                ('version', models.IntegerField(help_text='Version number (1, 2, 3, ...)')),
                ('description', models.CharField(blank=True, help_text='User-friendly description of this version', max_length=255)),
                ('prompt_text', models.TextField(help_text='The actual prompt content')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this prompt is currently active for API calls')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['prompt_type', 'name', '-version'],
                'indexes': [models.Index(fields=['prompt_type', 'is_active'], name='game_prompt_prompt__e8e48e_idx'), models.Index(fields=['prompt_type', 'name'], name='game_prompt_prompt__260f69_idx')],
                'unique_together': {('prompt_type', 'name', 'version')},
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='adventure_prompt',
            field=models.ForeignKey(help_text='Adventure/story prompt to use', limit_choices_to={'prompt_type': 'adventure'}, on_delete=django.db.models.deletion.PROTECT, related_name='configs_as_adventure', to='game.prompt'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='classifier_prompt',
            field=models.ForeignKey(blank=True, help_text='Prompt to use for detecting refusals', limit_choices_to={'prompt_type': 'classifier'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configs_as_classifier', to='game.prompt'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='game_ending_prompt',
            field=models.ForeignKey(blank=True, help_text='Prompt to use when game ends due to death/failure', limit_choices_to={'prompt_type': 'game-ending'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configs_as_game_ending', to='game.prompt'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='game_ending_turn_correction_prompt',
            field=models.ForeignKey(help_text='Turn correction prompt specifically for game-ending turns', limit_choices_to={'prompt_type': 'game-ending-correction'}, on_delete=django.db.models.deletion.PROTECT, related_name='configs_as_game_ending_turn_correction', to='game.prompt'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='turn_correction_prompt',
            field=models.ForeignKey(help_text='Turn correction prompt for regenerating refused or problematic turns', limit_choices_to={'prompt_type': 'turn-correction'}, on_delete=django.db.models.deletion.PROTECT, related_name='configs_as_turn_correction', to='game.prompt'),
        ),
        migrations.CreateModel(
            name='STTRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the recording', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the recording was uploaded')),
                ('file_path', models.CharField(help_text='Path to the stored audio file relative to MEDIA_ROOT', max_length=500)),
                ('mime_type', models.CharField(default='audio/webm', help_text='MIME type of the uploaded audio', max_length=100)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duration of the recording in seconds', null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('transcribed', 'Transcribed'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='uploaded', help_text='Current status of the recording', max_length=20)),
                ('transcript_text', models.TextField(blank=True, help_text='Transcribed text from the audio', null=True)),
                ('error_text', models.TextField(blank=True, help_text='Error message if transcription failed', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='game_sttrec_status_636f78_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], help_text='Who sent this message', max_length=10)),
                ('content', models.TextField(help_text='The message content')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for this message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(help_text='The conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='game.chatconversation')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='game_chatme_convers_1d4646_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('original_text', models.TextField(help_text='Original output from storyteller LLM')),
                ('refined_text', models.TextField(help_text='Final output after judge review')),
                ('was_modified', models.BooleanField(db_index=True, default=False, help_text='True if judge made changes, False if passed through unchanged')),
                ('was_refusal', models.BooleanField(default=False, help_text='True if this was detected as a refusal')),
                ('classifier_response', models.TextField(blank=True, help_text='Raw response from classifier model')),
                ('correction_prompt_used', models.ForeignKey(blank=True, help_text='Judge prompt used for correction (if refusal was detected)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_logs', to='game.prompt')),
                ('prompt_used', models.ForeignKey(blank=True, help_text='Which judge prompt was active during this request', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.prompt')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'was_modified'], name='game_auditl_timesta_6f922b_idx')],
            },
        ),
    ]
