# Generated by Django 5.1.4 on 2026-01-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='classifier_question',
            field=models.TextField(default='Is this a content policy refusal?', help_text='Question to ask the classifier along with the story turn text'),
        ),
    ]
