# Generated by Django 5.1.4 on 2026-01-15 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_apiprovider_llmmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of this difficulty profile (e.g., 'Easy', 'Brutal')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this difficulty curve')),
                ('function', models.TextField(help_text="Python expression: returns probability. Variables: x (turn), n (max_turns). Example: '0.05 + 0.35 * (x/n)**2'")),
                ('curve_points', models.JSONField(blank=True, help_text='Array of 5 probability values for 0%, 25%, 50%, 75%, 100% progress', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='difficulty',
            field=models.ForeignKey(blank=True, help_text='Difficulty profile for death probability curve', null=True, on_delete=django.db.models.deletion.PROTECT, to='game.difficultyprofile'),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Unique session identifier from OpenWebUI filter', max_length=32, unique=True)),
                ('turn_number', models.IntegerField(default=0, help_text='Current turn number (counts user messages after first assistant response)')),
                ('max_turns', models.IntegerField(default=20, help_text='Maximum turns for this game')),
                ('game_over', models.BooleanField(default=False, help_text='Whether this game has ended')),
                ('last_death_roll', models.FloatField(blank=True, help_text='Last random roll for death check (0.0-1.0)', null=True)),
                ('last_death_probability', models.FloatField(blank=True, help_text='Death probability on last turn', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(blank=True, help_text='Configuration snapshot when session started', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.configuration')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
