# Generated by Django 5.1.4 on 2026-01-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_configuration_game_ending_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='conversation_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='Hash of first user + first assistant message for lookup when session ID is stripped', max_length=32, null=True),
        ),
    ]
