# Generated by Django 5.1.4 on 2026-01-17 05:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='STTRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the recording', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the recording was uploaded')),
                ('file_path', models.CharField(help_text='Path to the stored audio file relative to MEDIA_ROOT', max_length=500)),
                ('mime_type', models.CharField(default='audio/webm', help_text='MIME type of the uploaded audio', max_length=100)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duration of the recording in seconds', null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('transcribed', 'Transcribed'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='uploaded', help_text='Current status of the recording', max_length=20)),
                ('transcript_text', models.TextField(blank=True, help_text='Transcribed text from the audio', null=True)),
                ('error_text', models.TextField(blank=True, help_text='Error message if transcription failed', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='game_sttrec_status_636f78_idx')],
            },
        ),
    ]
